// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateTOTPSecret() {
  return window['go']['main']['AuthService']['GenerateTOTPSecret']();
}

export function GetVaultPath() {
  return window['go']['main']['AuthService']['GetVaultPath']();
}

export function IsSetupComplete() {
  return window['go']['main']['AuthService']['IsSetupComplete']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['AuthService']['Login'](arg1, arg2, arg3);
}

export function SetupAccount(arg1, arg2, arg3) {
  return window['go']['main']['AuthService']['SetupAccount'](arg1, arg2, arg3);
}

export function ValidateTOTP(arg1, arg2) {
  return window['go']['main']['AuthService']['ValidateTOTP'](arg1, arg2);
}
