// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateTOTPSecret():Promise<string>;

export function GetVaultPath():Promise<string>;

export function IsSetupComplete():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SetupAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ValidateTOTP(arg1:string,arg2:string):Promise<boolean>;
