// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsPythonServerRunning() {
  return window['go']['main']['ChatService']['IsPythonServerRunning']();
}

export function ResetChat() {
  return window['go']['main']['ChatService']['ResetChat']();
}

export function SendMessage(arg1) {
  return window['go']['main']['ChatService']['SendMessage'](arg1);
}

export function StartPythonServer() {
  return window['go']['main']['ChatService']['StartPythonServer']();
}

export function StopPythonServer() {
  return window['go']['main']['ChatService']['StopPythonServer']();
}
