// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsPythonServerRunning():Promise<boolean>;

export function ResetChat():Promise<string>;

export function SendMessage(arg1:string):Promise<string>;

export function StartPythonServer():Promise<void>;

export function StopPythonServer():Promise<void>;
