// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteDrip(arg1:string,arg2:boolean,arg3:number,arg4:string):Promise<Record<string, any>>;

export function GetDripStatus():Promise<Record<string, any>>;

export function InitDripPortfolio(arg1:Record<string, number>):Promise<Record<string, any>>;

export function PlanDrip(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function SetDripKillSwitch(arg1:boolean):Promise<Record<string, any>>;
