// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteDrip(arg1, arg2, arg3, arg4) {
  return window['go']['main']['DripService']['ExecuteDrip'](arg1, arg2, arg3, arg4);
}

export function GetDripStatus() {
  return window['go']['main']['DripService']['GetDripStatus']();
}

export function InitDripPortfolio(arg1) {
  return window['go']['main']['DripService']['InitDripPortfolio'](arg1);
}

export function PlanDrip(arg1, arg2, arg3) {
  return window['go']['main']['DripService']['PlanDrip'](arg1, arg2, arg3);
}

export function SetDripKillSwitch(arg1) {
  return window['go']['main']['DripService']['SetDripKillSwitch'](arg1);
}
