// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchMarketData() {
  return window['go']['main']['MarketService']['FetchMarketData']();
}

export function GetMarketStatus() {
  return window['go']['main']['MarketService']['GetMarketStatus']();
}
