// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchMarketData():Promise<Array<Record<string, any>>>;

export function GetMarketStatus():Promise<Record<string, any>>;
