// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScannerBacktest():Promise<Record<string, any>>;

export function GetScannerPicks():Promise<Record<string, any>>;

export function GetScannerPortfolio():Promise<Record<string, any>>;

export function GetScannerStudy():Promise<Record<string, any>>;

export function RebalanceScanner(arg1:boolean,arg2:number,arg3:boolean):Promise<Record<string, any>>;

export function RefreshScanner():Promise<Record<string, any>>;
