// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePosition(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ExecuteOrder(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string):Promise<Record<string, any>>;

export function GetPositions():Promise<Record<string, any>>;

export function GetTradingSignals():Promise<Array<Record<string, any>>>;
