// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePosition(arg1, arg2) {
  return window['go']['main']['TradingService']['ClosePosition'](arg1, arg2);
}

export function ExecuteOrder(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['TradingService']['ExecuteOrder'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetPositions() {
  return window['go']['main']['TradingService']['GetPositions']();
}

export function GetTradingSignals() {
  return window['go']['main']['TradingService']['GetTradingSignals']();
}
